### ISSUE TITLE
Grid-by-grid scatter plot

### ISSUE THREAD

**Issue by ofithcheallaigh** [ofithcheallaigh/masters_project#29]
To try to better understand the data we are working, generate some scatter plots of the grid-wise data. 

Channel1 and Channel2 will make up the x- and y-axis.

# Todo
- [x] 2D plot of data
- [ ] Can I generate 3D plots?
- [ ] What about using R for visualisation?

**Comment by ofithcheallaigh** [comment]
2D plots have been generated, and will be presented next week.

Can't do a 3D plot, since there are only 1 channels. The MATLAB plots is fine, and time is moving on so I won't be looking into the R implementation.
